//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace universityERP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Http;

    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.studentCourses = new HashSet<studentCours>();
        }
    
        public int courseId { get; set; }
        [Required]
        public string courseName { get; set; }
        [Required]
        [DisplayName("Course Hours")]
        public Nullable<int> courseHours { get; set; }
        public Nullable<int> majorId { get; set; }
        public Nullable<int> doctorId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Major Major { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentCours> studentCourses { get; set; }
    }
}
